### ISSUE TITLE
The clicker does not work

### ISSUE THREAD

**Issue by Klaynight-dev** [TheHubGames/hub_games#11]
**Describe the bug**
The clicker does not work.

**To Reproduce**
1. Go to '[hubgames.studio](hhtps://hubgames.studio/Clicker)'
2. Click where you want or in the windows
3. See error

**Expected behavior**
The clicker does not work no matter where you click or in the window.

**Screenshots**
_``none``_

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser : chrome
- Version : 119.0.6045.124 (Build officiel) (64 bits)

**Comment by SelyanSel** [comment]
fixed [here](https://github.com/TheHubGames/hub_games/commit/cee0591d3d67e131acc0fceb6b4376512e48124f)

**Comment by Klaynight-dev** [comment]
nice
