### ISSUE TITLE
affichage bouton "jouer" sur ordinateur portable

### ISSUE THREAD

**Issue by J-A2b** [TheHubGames/hub_games#9]
selon moi il faudrait remplacer le css du bouton "jouer" par ça:

    .btn-primary {
    --tw-border-opacity: 1;
    border-color: hsl(var(--p) / var(--tw-border-opacity));
    --tw-bg-opacity: 1;
    background-color: hsl(var(--p) / var(--tw-bg-opacity));
    --tw-text-opacity: 1;
    color: hsl(var(--pc) / var(--tw-text-opacity));
    outline-color: hsl(var(--p) / 1);
    margin-left: 50%;
    margin-right: 50%;

il y a très certainement de meilleur solution mais voici la mienne.

**Comment by Klaynight-dev** [comment]
Tu peux mettre un screen stp

**Comment by J-A2b** [comment]
![image](https://github.com/TheHubGames/hub_games/assets/150968002/d2e110bd-a4d6-4079-966b-5abed41fca8c)
![hubgames studio](https://github.com/TheHubGames/hub_games/assets/150968002/7126780f-5c66-48eb-a905-27f17745a769)

**Comment by J-A2b** [comment]
voici les 2 versions, avec patch et sans patch

**Comment by Klaynight-dev** [comment]
dac le problème c'est juste l'affichage des containers faut revoir ça

**Comment by Klaynight-dev** [comment]
en plus j'ai fait une maj pour rajouté un système de favorie donc compliqué

**Comment by Klaynight-dev** [comment]
Problème résolu
